import numpy as np
my_list=[1,2,3]
arr=np.array(my_list)
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
print("Normal List: \n",my_list)
print("My list as array : \n",arr)
print("Matrix i.e., nested list as multi dimensional array: \n ",np.array(my_mat))
x=np.arange(0,10)
print("Np arrange: \n", x)
zero=np.zeros(3)
print("1D zeros array : \n",zero)
zero=np.zeros((2,3))
print("2X3 array of 0 : \n",zero)
equal_interval=np.linspace(0,5,10)
print ("0 to 5 10 intervals : \n",equal_interval)
equal_interval=np.linspace(0,5,100)
print ("0 to 5 100 intervals : \n",equal_interval)
id_mat=np.eye(4)
print("4x4 identity matrix : \n ",id_mat)
x=np.random.rand(5)
print("np random rand 1D size 5 ",x)
x=np.random.rand(5,5)
print("np random rand 2D size 5x5 ",x)
gaus_type=np.random.randn(2)
print("np random randn gauss type 1D size 2 ",gaus_type)
gaus_type=np.random.randn(4,4)
print("np random randn gauss type 2D size 4x4 ",gaus_type)
random_integer=np.random.randint(1,100)
print("1 random integer between 1 an 100 : \n ",random_integer)
random_integer=np.random.randint(1,100,10)
print("10 random integers between 1 an 100 : \n ",random_integer)
arr=np.arange(25)
print(arr)
ranarr=np.random.randint(0,50,10)
print(ranarr)
print("reshape arr : \n ",arr.reshape(5,5))
print("max and min of the random array : \n",ranarr.min()," and ",ranarr.max())
print("max index location : ",ranarr.argmax())
print("min index location : ",ranarr.argmin())
print("data type of array : ",arr.dtype)